tinyEnglish<-new.parser()
tinyEnglish<-add_rule(tinyEnglish, "N<-'Jack' / 'spam' / 'ship'")
tinyEnglish<-add_rule(tinyEnglish, "V<-'sank'/'threw'")
tinyEnglish<-add_rule(tinyEnglish, "ART<-'a'/'an'/'the'")
tinyEnglish<-add_rule(tinyEnglish, "ADJ<-'blue' / 'red' / 'green'")
tinyEnglish<-add_rule(tinyEnglish,  "NP<-ART? ' '+ (ADJ ' ')+ N")
tinyEnglish<-add_rule(tinyEnglish,  "S<-NP ' '+ V ' '+ NP ' '*")
apply_rule(tinyEnglish, "S", "the green spam  sank a red ship", record=TRUE)->res
tree(res)
plot(res)
